framework:
    ide: 'phpstorm://open?file=%%f&line=%l'
    secret: '%env(APP_SECRET)%'
    default_locale: hr
    csrf_protection: { enabled: true }
    #http_method_override: true
    #trusted_hosts: ~

    # uncomment this entire section to enable sessions
    session:
    #    # With this config, PHP's native session handling is used
        handler_id: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true
